### ISSUE TITLE
Review: MedicineAndSupplies and Signup

### ISSUE THREAD

**Issue by wjinyan** [med-warriors/project#13]
For this review, we will review the MedicineAndSupplies and Signup files.

## Review Branch
review-13

## Files to be reviewed
[MedicineAndSupplies.jsx](https://github.com/med-warriors/project/blob/master/app/imports/ui/pages/MedicineandSupplies.jsx)
[Signup.jsx](https://github.com/med-warriors/project/blob/master/app/imports/ui/pages/Signup.jsx)

## Checklists
- [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
- [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
- [JavaScript](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
- [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)

## Due Date
September 14, 2021

**Comment by tamtn2** [comment]
Architecture
- Naming convention

Design
- Consider putting more comments to "separate" big blocks of code 
- Put comments when appropriate, not after each line (LN 66-71, MedicineAndSuppies.JSX)
  
JS
- Rename "Stuff" collection (LN 73, MedicineAndSuppies.JSX)

React
- No comment.

**Comment by karenwong-kw** [comment]
UI-02: Perhaps fix the display so the layout can work on different devices
DE-01: Could use Uniforms for the Form
TU-01: Will need to implement tests

**Comment by jakeuyeda** [comment]
Sign Up page

TU-01: No tests done
UI-03: Make the submit a button


Medicine and supplies page

JS-01: Change name of stuffs to something more meaningful
TU-01: No tests done
UI-04: Provide example values

**Comment by duhkneelow** [comment]
**_MedicineAndSupplies.jsx_**

Architecture is OK
DE-05: Some comments are not necessary (Ex: L75 & L76)
JavaScript: Change Stuff
ESLint is OK
React is OK

**_Signup.jsx_**
TU-01: Testing required

**Comment by wjinyan** [comment]
## MedicineAndSupplies.jsx:
Architecture: naming and file conventions are followed
Design: could refactor and reduce duplicates
JS: no errors, but could have more comments, could make the tables into its own component
React: change stuffs collection to medicine
Needs testing

## Signup.jsx:
Architecture: naming and file conventions are followed
Design: there's repeat duplicate code
JS: no errors, but could have more comments
Needs testing

**Comment by wxh23285815** [comment]
MedicineAndSupplies.jsx
AR-03: not exactly consistent with existing directories
DE-04: Comment formatting, need comments for new code
JS-01:  file name is different to class
line 11: "class ListMedicine extends React.Component" and "Stuff" collection
UI-02: layout on the mobile screen sizes is different 
UI-03: table cell buttons for sorting - not work 

Signup.jsx
AR-03: not exactly consistent with existing directories
