### ISSUE TITLE
Review: Signup

### ISSUE THREAD

**Issue by wjinyan** [med-warriors/project#14]
For this review, we will review the Signup file.

### Review Branch
--------------------
review-14

### Files to be reviewed
--------------------
Signup.jsx

### Checklists
--------------------
- Architecture
- Design
- JavaScript
- React

### Due Date
--------------------
September 14, 2021

### Documentation
--------------------

**Comment by sydney-c7** [comment]
- interesting color choice for background
- maybe have buttons more defined with outline on outside
- good idea to confirm password

**Comment by cammoore** [comment]
The review issue should have links to the files and checklists. There
should be two files under review.

## Signup.jsx

RE-09: Prefer functions to classes, use the React hook 'useState' for
state. 

L59 - 134: Use uniforms.
