### ISSUE TITLE
Review: AddSupply and AddMedicine

### ISSUE THREAD

**Issue by wjinyan** [med-warriors/project#35]
## Overview

The focus for this code review will be centered around the AddSupply and AddMedicine pages.    
Please pay attention to:
* Javascript issues
* React components

## Review Branch

review-35

## Files to review

* [AddSupply](https://github.com/med-warriors/project/blob/master/app/imports/ui/pages/AddSupply.jsx)
* [AddMedicine](https://github.com/med-warriors/project/blob/master/app/imports/ui/pages/AddMedicine.jsx)

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

October 5, 2021

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by sydney-c7** [comment]
Add Medicine
- fix: when adding medicine as non-admin we get a notification that u need to be admin (good), but after we get another notification that it added
- input boxes are quite large possibly scaling down the input size so it's easier for the eyes to follow
Add Supplies
- fix: not found page
- javascript looks ok, might check collection and app connection

**Comment by ShengT-Jin** [comment]
AddSupply.jsx :
UI-01: We should reformate the page to make it cleaner for users to use.
UI-02: The navbar seems off on the mobile platform.
UI-04: Add a placeholder for each field.

TU-01: we need to implement test for this page.

AddMedicine.jsx :
UI-01: We should reformate the page to make it cleaner for users to use.
UI-02: The navbar seems off on the mobile platform.
UI-04: Add a placeholder for each field.

TU-01: we need to implement test for this page.

Consider adding drop-down list for common supply or medicine.

**Comment by wjinyan** [comment]
AddSupply.jsx:
DE-01: Change the forms to have grouping for the text fields instead of 1 column of text fields. 
DE-05 & DE-06: Could add more comments explaining code
UI-04: Have example values for text fields

AddMedicine.jsx:
DE-01: Change the layout to differentiate more from AddSupply. Group the text fields, include dropdowns or search function. The expiration date field doesn't work.
DE-05 & DE-06: Could add more comments explaining code
UI-04: Have example values for text fields
UI-07: Errors exist in the console

**Comment by karenwong-kw** [comment]
AddSupply & AddMedicine
Architecture is OK
Design is OK
UI-04: Provide example input for "Should Have", "Source", etc.
UI-05: Same as above, what is should have what is source
TA-01: no isDisplayed() test created for the pages
JS, Meteor, and React is OK

**Comment by duhkneelow** [comment]
**### AddMedicine.jsx**
Architecture is fine
Design is fine
JS: _Type is required_ after submit an entry for medicine table

**### AddSupply.jsx**
Architecture is fine
Design is fine
TU-01: Testing required

Overall, forms are fine, but in my opinion design can be different.
