### ISSUE TITLE
Review: CurrentSupplies.jsx / CurrentMedicine.jsx

### ISSUE THREAD

**Issue by karenwong-kw** [med-warriors/project#57]
## Overview

The focus for this code review will be centered around the CurrentSupplies and CurrentMedicine pages.    
Please pay attention to:
* Javascript issues
* React components

## Review Branch

review-57

## Files to review

* [CurrentSupplies](https://github.com/med-warriors/project/blob/master/app/imports/ui/components/CurrentSupplies.jsx)
* [CurrentMedicine](https://github.com/med-warriors/project/blob/master/app/imports/ui/components/CurrentMedicine.jsx)

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

November 2, 2021

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by wxh23285815** [comment]
CurrentMedicine.jsx
- Architecture is ok.
- Design
comments: dead code.
https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentMedicine.jsx#L9-L16 https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentMedicine.jsx#L69-L70
unnecessary spacing
https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentMedicine.jsx#L31
- Javascript is ok.
- React
Button has not run/working function.
https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentMedicine.jsx#L49
- Testing is ok.

CurrentSupplies.jsx
- Architecture is ok.
- Design is ok.
- Javascript is ok.
- React
Two types of color highlights are overlapping.
https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentSupplies.jsx#L30 https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentSupplies.jsx#L33
- Testing is ok.

**Comment by duhkneelow** [comment]
### CurrentMedicine.jsx
DE-03: Lines of dead code displayed (Ex: L9-L16 & L69-70).  Possibly not necessary when completed
RE-01: Green UPDATE button not working

### CurrentSupplies.jsx
RE-01/DE-07: Highlighting supply rows are essentially similar to each other (L30 & L33)

**Comment by ShengT-Jin** [comment]
CurrentMedicine:
DE-05: Remove the unnecessary comment at L9-L16.
UI-03: The Add button not working, and the update button is empty.
UI-07: The console generates errors.

CurrentSupplies:
UI-07: The console generates errors.

**Comment by karenwong-kw** [comment]
CurrentMedicine.jsx
D04: Dead commented out code
UI: Console error warnings 
_"modules.js?hash=d5ca79b4a8c14911031049d6e8f863b7835490fe:3977 Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>."_
_"Warning: validateDOMNesting(...): <button> cannot appear as a child of <tr>."_


CurrentSupplies.jsx
UI: Console error warnings 
_"modules.js?hash=d5ca79b4a8c14911031049d6e8f863b7835490fe:3977 Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>."_
_"Warning: validateDOMNesting(...): <button> cannot appear as a child of <tr>."_

**Comment by jakeuyeda** [comment]
CurrentMedicine.jsx
-DE-03: Eliminate dead code.
-DE-05: Ensure comments are appropriate still refering to stuff.
-RE-01: Green UPDATE button not working.
-UI-07: The console generates errors.


CurrentSupplies.jsx
-UI-07: The console generates errors.

**Comment by cammoore** [comment]
## CurrentSupplies.jsx

Should the thresholds be in a config file or collection?
https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentSupplies.jsx#L20

## CurrentMedicine.jsx

Delete commented out code.
https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentMedicine.jsx#L9-L16

Why use % for the thresholds? Maybe should use % in CurrentSupplies?

Comments are misleading.
https://github.com/med-warriors/project/blob/839e3077518bf5fc37deac7341cb0ac598fcd407/app/imports/ui/components/CurrentMedicine.jsx#L69-L70

**Comment by wjinyan** [comment]
## CurrentMedicine
- Large comment block
- Can use arrow function for the function in lines 19-21
- Update button does nothing
- Adjust the sizing of the buttons or make them in the same row so that the rows aren't too large in height
## CurrentSupplies
- May want to use shouldHave for the supply to determine the highlight colors
- Line 30 is repetitive, could maybe simplify

**Comment by tamtn2** [comment]
Both:
UI: Console errors
CurrentMedicine.jsx
- Useless code. Remove if not needed. Also, some comments refer to stuff.
- Certain buttons not working

CurrentSupplies.jsx
- Simplify comments into a block. Instead of commenting after each line, put them in a block to summarize that section.
